### ISSUE TITLE
Doesn't detect double-digit versioned packages

### ISSUE THREAD

**Issue by atlauren** [rustymyers/customBESAgentPkg#1]
`    if len(besPkgs) > 1:
        print "Found more than one package, choosing latest version."
    # Return the last package found, which should be latest verison
    return besPkgs[-1]`

This bit incorrectly selects, say, 9.5.8 if it's in the same directory as 9.5.13, because of asciibetical sorting.

**Comment by rustymyers** [comment]
@atlauren Try the latest commit. I added some additional functions for sorting the packages by version number properly.

**Comment by rustymyers** [comment]
Fixed in commit 9f62c5448d083e41423c20187ec93fe38f1352ec
